version: 4.30.5
build_image: registry.pyn.ru:5000/openjdk11-building:2019.03.14
docker_files:
  none: none
build_method: mvn_build
deploy_method: mvn_deploy
update_method: mvn_update
wiki_links:
- https://wiki.hh.ru/x/qo0eEQ
- https://github.com/hhru/nuts-and-bolts/releases
